spring:
  application:
    name: billing-app
  datasource:
    url: jdbc:postgresql://localhost:5432/billing
    username: billing
    password: pass
  jpa:
    show-sql: true
  liquibase:
    enabled: true
    contexts: schema, view, data, mock
    change-log: classpath:db/changelog/db.changelog-master.xml
    database-change-log-table: t_db_change_log
    database-change-log-lock-table: t_db_change_log_lock
    default-schema: billing
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${email}
    password: ${password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  server:
    port: 8082
